### ISSUE TITLE
How to measure network bandwidth using iperf3

### ISSUE THREAD

**Issue by junsoopark** [changjurhee/AONE#28]
- related Experiments : [experiment-1](../wiki/Milestone-%231#experiment-1)

**Comment by du0san** [comment]
bandwidth + jitter or drop 설정 후 iperf를 이용해서 네트워크 가용 대역폭 측정
 ==> 테스트 조건 iperf3를 활용한 network 환경 bandwidth 측정

측정 결과 : Idle상태에서 Max Bandwidth가 30Mbps로 측정됨
![image](https://github.com/changjurhee/AONE/assets/85091738/e4ac357b-8d38-4334-a793-9445cffa7a22)

테스트 조건 : 
Iperf version : iPerf 3.1.3
Server 측  command : iperf3.exe -s
Client 측  command : iperf3.exe -c IP -p PORT -w 2m -t 10s -i 1s


 jitter or drop 설정 사항은 wifi 2.4Ghz 사용 가능 여부 확인 후 측정 예정
