### ISSUE TITLE
Media | Find the correlation between network bandwidth and video quality.

### ISSUE THREAD

**Issue by changjurhee** [changjurhee/AONE#33]
- related document : [experiment-2](https://github.com/changjurhee/AONE/wiki/Milestone-%231#experiment-2)

**Comment by changjurhee** [comment]
![Image](https://github.com/changjurhee/AONE/assets/3052540/6743c959-9ac8-416b-bfe5-fd69bf377a02)

**Comment by changjurhee** [comment]
- Dan's Query : 
  - We have tested with PI4 to find the correlation between network bandwidth and video quality. 
  - We have some issue when we have connection with 2 different SSID such as LG_TEST_NETWORK_1_AONE and LG_TEST_NETWORK_2_AONE.

**Comment by changjurhee** [comment]
> Team 1, 
> 
> Wifi routers have different channels. Here's a [link with an explanation](https://www.minim.com/blog/wifi-channels-explained).
> Please go to Dan's live session and search the transcript for channel. 
> 
> Paulo

**Comment by changjurhee** [comment]
- Dan's Kickoff speaking
- 
> See? Both teams. There are 2 access points, and everybody see that there's 2 access points available.
> Okay, now.
> when you want to test to see how well your machine works in
> a
> environment where the network may not be perfect. Okay, where there could be a lot of jitter or packet lost.
> You connect one machine to network one, and you connect the second machine to network 2,
> and then. you know. your applications will communicate
> to each other. Okay, via these 2 networks. But just one application.

**Comment by codekistone** [comment]
![image](https://github.com/changjurhee/AONE/assets/101652051/02bd7b7c-29d3-40da-b65b-7dfe5f006353)

**Comment by du0san** [comment]
AP1과 AP2간의 network bandwidth가 1Mbps 측정되어서 해당 환경에서 video quality 측정 테스트를 진행함
하지만 이론상 jitter나 drop없이 송부되어야 할 ultra low에서도 동일하게  jitter나 drop이 발생되며 해당 video quality가 이미 낮은 상태임으로 jitter나 drop에 개선 여부 확인이 불가합니다.
  이에 본 테스트 항목은 추가 진행이 어려울 것으로 보입니다.

**Comment by changjurhee** [comment]
- dan live session request 10:00

**Comment by changjurhee** [comment]
- 상기 테스트 결과를 정리 요약 하면 아래와 같습니다. 

team | machine 1 | machine 2 | bandwidth
--|--|--|--
1 | AP1 | AP1 | 30 Mbps
1 | AP1 | AP2 | < 1 Mbps
3 | AP1 | AP 1 |  < 23Mbps
3 | AP2 | AP1 | < 8 Mbps
3 | AP2 | AP2 | < 4Mbps

**Comment by changjurhee** [comment]
![Image](https://github.com/changjurhee/AONE/assets/3052540/c85165f2-a63f-4a8f-98fe-781561562593)


![Image](https://github.com/changjurhee/AONE/assets/3052540/1377ac83-05ef-4cd2-bbbb-bb5678d15aa6)

**Comment by changjurhee** [comment]
![Image](https://github.com/changjurhee/AONE/assets/3052540/681085ff-729c-4cfd-8d81-aee6b8ca4781)

**Comment by changjurhee** [comment]
- staff에게 Pi Spare 문의 : Pi가 한 개 남아 있어 그걸로 테스트 해볼 예정임.

**Comment by du0san** [comment]
새로 전달받은 라즈베리파이에서 측정 결과는 정상 수준으로 확인됩니다.
![image](https://github.com/changjurhee/AONE/assets/85091738/6d789304-f7a6-4783-8c1d-373523d2a22c)

**Comment by du0san** [comment]
새로 전달받은 AP로 각 brandwidth별 video quality 확인 결과 하기와 같은 측정되었습니다.

suggested   bitrate | selected image   resolution | 2 | 1 | 0.5
-- | -- | -- | -- | --
60   kbps | 320   x 240 | OK | OK | OK
120   kbps | 320   x 240 | OK | OK | OK
250   kbps | 480   x 360 | OK | OK | OK
500   kbps | 640   x 480 | OK | OK | NG
1024   kbps | 640   x 480 | OK | NG | NG

 PC 수량 문제로 star대신 mech로 측정을 진행하였으며 OK/NG판단 기준은 image delay 발생 유무로 확인하였습니다.

 NG가 되는 timing에 해당 하는 시점의 결과는 하기와 같습니다.
bitrate (1024 kbps), Bandwidth(1Mbps)
![image](https://github.com/changjurhee/AONE/assets/85091738/d4ed1895-c238-4569-8a0f-13dffdf989ac)

bitrate (500 kbps), Bandwidth(0.5Mbps)
![image](https://github.com/changjurhee/AONE/assets/85091738/70b2ff7e-315d-49aa-bc4e-cfb3a7219def)

**Comment by du0san** [comment]
기존 측정치 기반으로 star 측정 결과를 보면 하기와 같습니다.

suggested   bitrate | selected image resolution | required target bandwidth ((s.   bitrate + 300) * 4) | 3 | 2 | 1 | 0.5
-- | -- | -- | -- | -- | -- | --
60 kbps | 320   x 240 | 1440   kbps | OK | OK | OK | OK
120 kbps | 320   x 240 | 1680   kbps | OK | OK | OK | OK
250 kbps | 480   x 360 | 2200   kbps | OK | OK | OK | NG
500 kbps | 640   x 480 | 3200   kbps | OK | OK | NG | NG
1024 kbps | 640   x 480 | 5296   kbps | NG | NG | NG | NG

**Comment by changjurhee** [comment]
- 월요일에 실제 필요한 수량의 피시를 연결하여 STAR 방식으로 테스트를 다시 한번 해보도록 합시다. 수고 하셨습니다.

**Comment by du0san** [comment]
금일 STAR 방식으로 측정한 결과 공유드립니다.
1~2군데를 제외하고는 다 mech로 추정한 결과가 확인되었습니다.

suggested   bitrate | selected image   resolution | required target   bandwidth ((s. bitrate + 300) * 4) | 3 | 2 | 1 | 0.5
-- | -- | -- | -- | -- | -- | --
60   kbps | 320   x 240 | 1440   kbps | OK | OK | OK | OK
120   kbps | 320   x 240 | 1680   kbps | OK | OK | OK | NG
250   kbps | 480   x 360 | 2200   kbps | OK | OK | OK | NG
500   kbps | 640   x 480 | 3200   kbps | OK | NG(△) | NG | NG
1024   kbps | 640   x 480 | 5296   kbps | NG(△) | NG | NG | NG

일부 항목에서는 약간의 latency가 추가되는 수준이여서 △으로 표시하였습니다.
  500 kbps와 bandwidth 2 Mbps
![image](https://github.com/changjurhee/AONE/assets/85091738/1a98cdb6-2a45-4882-b9fb-ea427b7a71c8)
  1024 kbps와 bandwidth 3 Mbps
![image](https://github.com/changjurhee/AONE/assets/85091738/974ec6ad-fb41-413e-9d84-69bbc2b7858d)

 또한 wireshark로 packet 속도를 측정한 결과는 하기와 같습니다.
AP에서 제한 bandwidth와 정확히 mapping되지는 않습니다만, packet속도가 늦어지는 경우에는 확실히 이슈가 발생되는 것을 확인 할 수 있었습니다.
bitrate | resolution | 3 | 2 | 1 | 0.5
-- | -- | -- | -- | -- | --
60 Kbps | 320x240 | 770 Kbps | 774 Kbps | 768 Kbps | 776 Kbps
120 Kbps | 320x240 | 1010 Kbps | 1002 Kbps | 1011 Kbps | 1002 Kbps
250 Kbps | 480x360 | 1603 Kbps | 1601 Kbps | 1601 Kbps | 1283 Kbps
500 Kbps | 640x480 | 2647 Kbps | 2626 Kbps | 2263 Kbps | 1750 Kbps
1024 Kbps | 640x480 | 4693 Kbps | 4364 Kbps | 3252 Kbps | 2788 Kbps

**Comment by changjurhee** [comment]
```
#! /bin/bash
sudo tc qdisc add dev wlan0 root netem rate 3Mbit
sudo tc qdisc add dev wlan1 root netem rate 3Mbit
```
```
#! /bin/bash
sudo tc qdisc add dev wlan0 root netem rate 2Mbit
sudo tc qdisc add dev wlan1 root netem rate 2Mbit
```
```
#! /bin/bash
sudo tc qdisc add dev wlan0 root netem rate 1Mbit
sudo tc qdisc add dev wlan1 root netem rate 1Mbit
```
```
#! /bin/bash
sudo tc qdisc add dev wlan0 root netem rate 500Kbit
sudo tc qdisc add dev wlan1 root netem rate 500Kbit
```

**Comment by du0san** [comment]
추가로 gstreamer test command는 GstreamerTool_v0_7.exe를 사용하였습니다.
사용한 command는 하기와 같습니다. 
ex) 1024 kbps

client:
```powershell
gst-launch-1.0 ksvideosrc device-index=0 !"video/x-raw,width=640,height=480,framerate=30/1"! videoconvert ! videoscale ! video/x-raw,width=640,height=480 ! x264enc tune=zerolatency key-int-max=30  bitrate=1024 ! rtph264pay !  queue ! udpsink host=192.168.3.7 port=5297 udpsrc port=5317 ! "application/x-rtp, payload=96" ! rtph264depay ! h264parse ! avdec_h264 ! videoconvert ! queue ! fpsdisplaysink sync=false wasapi2src low-latency=true ! audioconvert ! audioresample ! opusenc ! rtpopuspay !  queue ! udpsink host=192.168.3.7 port=6297 sync=false processing-deadline=0 udpsrc port=6317 !  "application/x-rtp,payload=96,media=audio,encoding-name=OPUS" ! rtpopusdepay ! opusdec plc=true min-latency=2000000 ! audioresample ! audioconvert ! queue ! wasapi2sink low-latency=true sync=true 
``` 

server:
```powershell
gst-launch-1.0 compositor name=mix sink_0::xpos=0 sink_0::ypos=0 sink_0::width=640  sink_0::height=480 sink_1::xpos=640 sink_1::ypos=0 sink_1::width=640  sink_1::height=480 ! videoconvert ! x264enc tune=zerolatency key-int-max=30  bitrate=1024 ! rtph264pay !  tee name=t udpsrc port=5297 ! "application/x-rtp, payload=96" ! rtph264depay ! h264parse ! avdec_h264 ! videoconvert ! queue ! mix. udpsrc port=5322 ! "application/x-rtp, payload=96" ! rtph264depay ! h264parse ! avdec_h264 ! videoconvert ! queue ! mix. t. ! queue !   udpsink host=192.168.2.8 port=5317 t. ! queue !   udpsink host=192.168.2.2 port=5292 audiomixer name=m m. ! audioconvert ! audioresample ! opusenc ! rtpopuspay !  tee name=ta udpsrc port=6297 !  "application/x-rtp,payload=96,media=audio,encoding-name=OPUS" ! rtpopusdepay ! opusdec plc=true min-latency=2000000 ! audioresample ! audioconvert ! queue ! m. udpsrc port=6322 !  "application/x-rtp,payload=96,media=audio,encoding-name=OPUS" ! rtpopusdepay ! opusdec plc=true min-latency=2000000 ! audioresample ! audioconvert ! queue ! m. ta. ! queue !   udpsink host=192.168.2.8 port=6317 sync=false processing-deadline=0 ta. ! queue !   udpsink host=192.168.2.2 port=6292 sync=false processing-deadline=0 
```

**Comment by changjurhee** [comment]
> sudo tc qdisc add dev wlan0 root netem rate 3Mbit 
>> 3Mbit 의미가 무엇인가 ?

**Comment by changjurhee** [comment]
- Test Connection 
  - server : 5G
  - client 1/2 : 2.4G
