### ISSUE TITLE
Media | Verify that receiver can improve paket loss problems using duplication / reordering.

### ISSUE THREAD

**Issue by changjurhee** [changjurhee/AONE#35]
- related document : [experiment-4](../wiki/Milestone-%231#experiment-4)

**Comment by junsoopark** [comment]
# test environment
* Audio RTP packets sender(a process) and Audio RTP packets receiver(a process) running on the same computer
* Use [netsim](https://gstreamer.freedesktop.org/documentation/netsim/index.html?gi-language=c) element to simulate network jitter and drop. Insert netsim element prior to rtpjitterbuffer element.
* Use properties for simulating network jitter. please refer to [netsim](https://gstreamer.freedesktop.org/documentation/netsim/index.html?gi-language=c)
  * `allow-reordering=true`
  * `delay-distribution=normal` means Gaussian distribution of delays.
  * `delay-probability=0.1` means 10% of packets are affected.
  * `max-delay=400` means 400ms
  * `drop-probability=0.2` means 20% of packets are dropped.
* Use latency property of [rtpjitterbuffer](https://gstreamer.freedesktop.org/documentation/rtpmanager/rtpjitterbuffer.html?gi-language=c)
  * `latency=500` means 500ms.
* Commands
  * sender : `gst-launch-1.0 audiotestsrc ! opusenc frame-size=10 ! rtpopuspay ! udpsink host=127.0.0.1 port=5000`
  * receiver : `gst-launch-1.0 --gst-debug-no-color udpsrc port=5000 ! "application/x-rtp,payload=96,media=audio,encoding-name=OPUS" ! netsim allow-reordering=true delay-distribution=normal delay-probability=0.1 max-delay=400 drop-probability=0.2 ! rtpjitterbuffer latency=500 do-lost=true ! rtpopusdepay ! opusdec plc=true min-latency=5000000 ! fakesink sync=true processing-deadline=0`

  * receiver for debugging : `GST_DEBUG=GST_SCHEDULING:0,rtpjitterbuffer:7,opusdec:5,GST_SCHEDULING:5 gst-launch-1.0 --gst-debug-no-color udpsrc port=5000 ! "application/x-rtp,payload=96,media=audio,encoding-name=OPUS" ! netsim allow-reordering=true delay-distribution=normal delay-probability=0.1 max-delay=400 drop-probability=0.2 ! rtpjitterbuffer latency=500 do-lost=true ! rtpopusdepay ! opusdec plc=true min-latency=5000000 ! fakesink sync=true processing-deadline=0 2>&1 | grep -i "missing packets:\|old packet received\|GstRTPPacketLost"`

**Comment by junsoopark** [comment]
# Test Result
Verified when signaling GstRTPPacketLost event to `opusdec` through pipe `opusdec` created PLC frame to compensate the packet loss.
```
0:00:04.244861000 50744 0x7fafbb0f5180 DEBUG        rtpjitterbuffer gstrtpjitterbuffer.c:3890:pop_and_push_next:<rtpjitterbuffer0> Pushing event custom-downstream event: 0x7fafbc0242d0, time 99:99:99.999999999, seq-num 222, GstRTPPacketLost, seqnum=(uint)53598, timestamp=(guint64)3624821945, duration=(guint64)10000181, retry=(uint)0;, seqnum 53598
0:00:04.244890000 50744 0x7fafbb0f5180 DEBUG                opusdec gstopusdec.c:621:opus_dec_chain_parse_data:<opusdec0> missing buffer, doing PLC duration 0:00:00.010000181 plus leftover 0:00:00.000866500
0:00:04.244897000 50744 0x7fafbb0f5180 DEBUG                opusdec gstopusdec.c:658:opus_dec_chain_parse_data:<opusdec0> calculated PLC frame length: 0:00:00.010000000 num frame samples: 480 new leftover: 0:00:00.000866681
0:00:04.254254000 50744 0x7fafbb0f5180 DEBUG        rtpjitterbuffer gstrtpjitterbuffer.c:3890:pop_and_push_next:<rtpjitterbuffer0> Pushing event custom-downstream event: 0x7fafbb1122c0, time 99:99:99.999999999, seq-num 224, GstRTPPacketLost, seqnum=(uint)53599, timestamp=(guint64)3634822126, duration=(guint64)9999638, retry=(uint)0;, seqnum 53599
0:00:04.254374000 50744 0x7fafbb0f5180 DEBUG                opusdec gstopusdec.c:621:opus_dec_chain_parse_data:<opusdec0> missing buffer, doing PLC duration 0:00:00.009999638 plus leftover 0:00:00.000866681
0:00:04.254394000 50744 0x7fafbb0f5180 DEBUG                opusdec gstopusdec.c:658:opus_dec_chain_parse_data:<opusdec0> calculated PLC frame length: 0:00:00.010000000 num frame samples: 480 new leftover: 0:00:00.000866319
```

**Comment by junsoopark** [comment]
# Consequences
Originally we're going to duplicate, on application side, lost packets that are caused by being dropped  from network. But we've found that `opusdec` has a functionality for handling packet loss concealment(plc) so we decided to use the functionality.
We've done some tests and verified that `opusdec` creates new packets for the lost packets as the result. And we'll conduct more tests to check how well the plc mechanism works.
