### ISSUE TITLE
Implementation Generation Script Tool

### ISSUE THREAD

**Issue by changjurhee** [changjurhee/AONE#38]
- To generate a script for GStreamer CLI
- Implementation generation script tool w/ python
- [discussion for preparation](https://github.com/changjurhee/AONE/discussions/26)
- [discussion for test environment](https://github.com/changjurhee/AONE/discussions/29)

**Comment by changjurhee** [comment]
![image](https://github.com/changjurhee/AONE/assets/3052540/7fbc1a5c-b601-4669-96ab-eaf7a2340fb6)

**Comment by du0san** [comment]
Update script for support audio
![image](https://github.com/changjurhee/AONE/assets/85091738/915cf9d0-53a1-496b-939d-10f4ed00a870)
