### ISSUE TITLE
raspberryPi connect

### ISSUE THREAD

**Issue by codekistone** [changjurhee/AONE#39]
[Local connection]
ssh lg@raspberrypi.local
PW : lg

[AP connection]
ssh lg@192.168.2.1
PW : lg

**Comment by junsoopark** [comment]
패킷 드랍을 위한 iptables 명령어 사용법.  

https://linuxstory1.tistory.com/entry/iptables-%EA%B8%B0%EB%B3%B8-%EB%AA%85%EB%A0%B9%EC%96%B4-%EB%B0%8F-%EC%98%B5%EC%85%98-%EB%AA%85%EB%A0%B9%EC%96%B4
